Lockdown
sahil-kale/tron-discord-bot pull request #112
Opened 2020-12-22 23:24 UTC by Carson-Bay

2020-12-22 23:27 UTC, sahil-kale requested changes

2020-12-22 23:27 UTC, sahil-kale commented on commands/lockdown.py
> +        replyEmbed = _embedMessage.create("Lockdown reply", "Something Fucky Happened", "red")
Please change wording here

2020-12-22 23:27 UTC, sahil-kale commented on commands/lockdown.py
> +        replyEmbed = _embedMessage.create("Locked Reply", "Invalid Permissions", "red")
String should be Lockdown Reply

2020-12-23 02:31 UTC, zaydtahir requested changes
Can you add the two commands to $help? (Make sure they are in alphabetical order and under the admin section or Sahil will get angry)

2020-12-23 20:53 UTC, sahil-kale approved these changes
Approved

2020-12-23 21:05 UTC, zaydtahir requested changes
Just fix those two things and it should be good

2020-12-23 21:05 UTC, zaydtahir commented on commands/help.py
> +    _embedMessage.add_field(helpMessage, commandPrefix2 + "lockdown", "Sets send message permissions to false for specified role\nEx: " + commandPrefix2 + "lockdown " + "Tron", False)
The parameters of the command should be in the first string, like it is for all the other commands

2020-12-23 21:05 UTC, zaydtahir commented on commands/help.py
> +    _embedMessage.add_field(helpMessage, commandPrefix2 + "unlock", "Sets send message permissions to True for specified role\nEx: " + commandPrefix2 + "unlock " + "Tron", False)
Same issue as previous comment

2020-12-23 21:46 UTC, sahil-kale requested changes
Please resolve merge conflicts on main before merging

2020-12-24 00:08 UTC, sahil-kale approved these changes
Looks good to me with Zayd's approval

2020-12-24 21:24 UTC, zaydtahir approved these changes
Looks good

2020-12-24 21:25 UTC, merged